// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1773421518);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1773421518);
user_pref("app.update.lastUpdateTime.glean-addons-daily", 1773421518);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1773421518);
user_pref("app.update.lastUpdateTime.region-update-timer", 1773421518);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1773421488);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1773421518);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1773421518);
user_pref("browser.aboutwelcome.didSeeFinalScreen", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "b35aec1f-17e0-49e7-ace4-81f70bfff269");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1773421488);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1773421486);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 163);
user_pref("browser.newtabpage.activity-stream.impressionId", "{978f2d01-35da-4161-bbe0-2db7a4a15716}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1773421488199");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1773443088199");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20260203190549");
user_pref("browser.startup.homepage_override.mstone", "147.0.3");
user_pref("browser.startup.lastColdStartupCheck", 1773421488);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\",\"screenshot-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\"],\"currentVersion\":23,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 6);
user_pref("captchadetection.lastSubmission", 1773421);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "f97d1c77-b2bb-4ea2-a267-7ced9063d284");
user_pref("datareporting.dau.cachedUsageProfileID", "7cf92c47-3ba4-4233-8594-1e03fef20a40");
user_pref("distribution.Manjaro.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "147.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260203190549");
user_pref("extensions.lastAppVersion", "147.0.3");
user_pref("extensions.lastPlatformVersion", "147.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webcompat.enable_interventions", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"3b6010ec-5695-4337-b271-42c6b82cd55a\",\"formautofill@mozilla.org\":\"b1d4fd6f-81b5-4f56-9505-507323d33825\",\"ipp-activator@mozilla.com\":\"167b9f7e-4c47-4368-b3f4-0aa0617bc400\",\"pictureinpicture@mozilla.org\":\"683eb2ab-1c45-43e5-9aba-3f190c4e2c48\",\"addons-search-detection@mozilla.com\":\"66e9f44f-a7ee-442e-a74d-ab0871f501d9\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"b3ab0fef-80b8-4904-8c41-407d074cfbd7\",\"default-theme@mozilla.org\":\"ddaf2bc7-cd27-4f62-8fe7-20e2205049f2\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: 2152398878, errorCode: 2, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1773421518);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1773421518);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 3);
user_pref("nimbus.migrations.init-started", 0);
user_pref("nimbus.profileId", "10d6e063-aa32-4493-8510-b3e3db43c844");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.visibility", "hide-sidebar");
user_pref("telemetry.fog.init_on_shutdown", false);
user_pref("toolkit.profiles.storeID", "169c0140");
user_pref("toolkit.startup.last_success", 1773421485);
user_pref("toolkit.telemetry.cachedClientID", "82e59645-c7b0-4493-9755-82416d0a92c1");
user_pref("toolkit.telemetry.cachedProfileGroupID", "3779a2bf-8756-492a-9fd7-0562fdb06722");
user_pref("toolkit.telemetry.previousBuildID", "20260203190549");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
