#!/usr/bin/env bash

BAT=$(cat /sys/class/power_supply/BAT0/capacity)
STATUS=$(cat /sys/class/power_supply/BAT0/status)

if [[ "$BAT" -le 87 && "$STATUS" == "Discharging" ]]; then
    brightnessctl set 5%
fi
